name: CI/CD - MediConnect

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout Code
      uses: actions/checkout@v4

    # Docker Hub Login
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Frontend Build & Push
    - name: Build & Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mediconnect-frontend:latest

    # Backend Build & Push
    - name: Build & Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mediconnect-backend:latest

    # AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Install kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    # Connect to EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region ap-south-1 \
          --name mediconnect-cluster

    # Restart Deployments
    - name: Restart Kubernetes Deployments
      run: |
        kubectl rollout restart deployment frontend -n mediconnect
        kubectl rollout restart deployment backend -n mediconnect

    # Wait until rollout completes
    - name: Verify Rollout
      run: |
        kubectl rollout status deployment/frontend -n mediconnect
        kubectl rollout status deployment/backend -n mediconnect
